export const METERING_REASON_NODE_UNAVAILABLE = "NODE_METERING_UNAVAILABLE";
export const METERING_REASON_MAPPING_MISSING = "NODE_USER_MAPPING_MISSING";
export const METERING_REASON_SAMPLE_MISSING = "NODE_USER_SAMPLE_MISSING";
export const METERING_REASON_COUNTER_ROLLBACK = "NODE_COUNTER_ROLLBACK";
