import type { Dispatch, SetStateAction } from "react";
import type { AdminLeaseRevocationJobDto, AdminNodeCommandQueueDto, AdminSubscriptionRecordDto, AdminTeamRecordDto, AdminTeamUsageRecordDto, AdminUserRecordDto } from "@chordv/shared";
import type { LeaseRevocationQueueFilter } from "../../utils/admin-queue-filters";
import type { TeamFormState, TeamMemberFormState } from "../../utils/admin-forms";

export type UsersPageProps = {
  searchValue: string;
  onSearchChange: (value: string) => void;
  userTab: "personal" | "team";
  onUserTabChange: (value: "personal" | "team") => void;
  users: AdminUserRecordDto[];
  filteredTeams: AdminTeamRecordDto[];
  subscriptions: AdminSubscriptionRecordDto[];
  allSubscriptions: AdminSubscriptionRecordDto[];
  allUsers: AdminUserRecordDto[];
  leaseRevocationJobs: AdminLeaseRevocationJobDto[];
  nodeCommandQueue: AdminNodeCommandQueueDto;
  leaseRevocationRetryBusyKey: string | null;
  teamUsageByTeamId: Record<string, AdminTeamUsageRecordDto[]>;
  teamUsageLoadingByTeamId: Record<string, boolean>;
  teamUsageErrorByTeamId: Record<string, string | null>;
  actionBusyKey: string | null;
  teamInlineEditorId: string | null;
  teamMemberInlineEditor: { teamId: string; memberId: string | null } | null;
  teamProfileBusyKey: string | null;
  teamMemberBusyKey: string | null;
  teamForm: TeamFormState;
  setTeamForm: Dispatch<SetStateAction<TeamFormState>>;
  teamMemberForm: TeamMemberFormState;
  setTeamMemberForm: Dispatch<SetStateAction<TeamMemberFormState>>;
  buildTeamMemberOptions: (currentUserId?: string) => Array<{ value: string; label: string }>;
  onOpenUserDrawer: (userId: string) => void;
  onCreateSubscriptionForUser: (user: AdminUserRecordDto) => void;
  onOpenTeamSubscriptions: (team: AdminTeamRecordDto) => void;
  onOpenRenewDrawer: (subscriptionId: string) => void;
  onOpenChangePlanDrawer: (subscriptionId: string) => void;
  onOpenAdjustDrawer: (subscriptionId: string) => void;
  onOpenNodeAccessEditor: (subscriptionId: string, ownerLabel: string) => void;
  onResetSubscriptionTraffic: (subscriptionId: string, ownerLabel: string, userId?: string) => void;
  resetTrafficBusyKey: string | null;
  onLoadTeamUsage: (teamId: string, options?: { force?: boolean }) => void;
  onOpenTeamUsageDetail: (payload: {
    teamName: string;
    userDisplayName: string;
    userEmail: string;
    entry: AdminTeamUsageRecordDto;
  }) => void;
  onOpenTeamInlineEditor: (teamId: string) => void;
  onCloseTeamInlineEditor: () => void;
  onSaveTeamInlineEditor: (teamId: string) => void;
  onOpenTeamMemberInlineEditor: (teamId: string, memberId?: string | null) => void;
  onCloseTeamMemberInlineEditor: () => void;
  onSaveTeamMemberInlineEditor: () => void;
  onDeleteTeamMember: (teamId: string, memberId: string) => void;
  onToggleUserStatus: (userId: string, nextStatus: "active" | "disabled", displayName: string) => void;
  onToggleTeamUserStatus: (userId: string, nextStatus: "active" | "disabled", displayName: string) => void;
  onDisconnectUser: (userId: string, displayName: string, source?: "personal" | "team-member") => void;
  onRetryLeaseRevocationJob: (jobId: string) => void;
  onOpenLeaseRevocationQueue: (filter?: LeaseRevocationQueueFilter) => void;
};
